apiVersion: v1
kind: Service
metadata:
 name: minecraft-server2-lb
spec:
 type: LoadBalancer
 ports:
 - protocol: TCP
   port: 25565
   targetPort: 25565
   name: game
 - protocol: TCP
   port: 25575
   targetPort: 25575
   name: rcon
 selector:
   app: minecraft-server2
